// Mocks generated by Mockito 5.4.4 from annotations
// in movie_hub/test/unit_testing/authentication/shared/mocks/user_credential/user_credential.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
part of 'user_credential.dart';

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserCredentialTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredentialTest extends Mock implements UserCredentialTest {
  MockUserCredentialTest() {
    throwOnMissingStub(this);
  }
}
